### ISSUE TITLE
[Client] Customizable "extra" type definition

### ISSUE THREAD

**Issue by DWyatb** [UniCourse-TW/Backend#51]
extra type definition(等後端修改完成 前端需修改 FullScreenCard )

![Image](https://user-images.githubusercontent.com/98510916/204485814-4e296c2d-6273-4306-a0ab-def9d2b32bec.png)

**Comment by JacobLinCool** [comment]
After reviewing the relevant types, I believe it would be more appropriate to implement some helper function to check for the "extra" field when using it.

In this case, I would suggest using a typed `computed` since there is only one course in the component.

Like this:

```ts
let course: EndpointResponseBody<`courses/${string}`>;
const extra = computed<{ restrict: string; comment: string }>(() => {
    if (!course) {
        return { restrict: "", comment: "" };
    }

    const ex = course.extra && typeof course.extra === "object" && !Array.isArray(course.extra) ? course.extra : {};

    return {
        restrict: typeof ex.restrict === "string" ? ex.restrict : "",
        comment: typeof ex.comment === "string" ? ex.comment : "",
    };
});

init();

async function init() {
    course = await uni.req(`courses/${props.course}`);
}
```

Since `extra` can be almost anything in different cases, I think the type checker should be implemented independently of the core client library.

@UniCourse-TW/frontend

**Comment by JacobLinCool** [comment]
@DWyatb What do you think?

**Comment by skyhong2002** [comment]
This issue has not been updated for a while. Request @DWyatb to reply.
