### ISSUE TITLE
Encounter 500 server error when create post

### ISSUE THREAD

**Issue by uier** [UniCourse-TW/Backend#55]
In the source I saw to create a post we only required: `type`, `title`, `content`, `tags`
https://github.com/UniCourse-TW/Backend/blob/bad65172984218678cc24dde51ea6f76b0d83062/src/api/posts/index.ts#L78-L113

But I got 500 server error in the following request.

Request body (I assumed `course` will be ignore):
```
{
  "type": "review",
  "title": "This is title",
  "content": "This is content",
  "tags": [
    "testing",
    "first"
  ],
  "course": {
    "year": 0,
    "term": 0,
    "serial": 0,
    "name": "",
    "teacher": "",
    "rating": {
      "sweetness": 0,
      "easiness": 0,
      "usefulness": 0
    }
  }
}
```

Response:
```
{"error":"Internal Server Error. ID: #clbgxs6qg00050hnyb3c90n1m"}
```

**Comment by JacobLinCool** [comment]
This is an unexpected result.

The expected result is an HTTP 400 error, which tells you that the `course` field should not be an object.

Some clarifications:
- Course linkage would be ignored **only when it is not the in the post data**
- The `course` field should be a `string` as the course id if the linkage is presented
- The client will not strip anything, so you should set `course` to `undefined` in this case

I just checked the error details, it seems that the type error was raised as expected but the catcher didn't recognize it as a type error:

The type check didn't pass, and a `ZodError` was raised:

https://github.com/UniCourse-TW/Backend/blob/bad65172984218678cc24dde51ea6f76b0d83062/src/api/posts/index.ts#L93

The raised `ZodError` was not recognized as `z.ZodError`:

https://github.com/UniCourse-TW/Backend/blob/bad65172984218678cc24dde51ea6f76b0d83062/src/middlewares.ts#L88-L101

I think it was caused by some re-import things. 

@UniCourse-TW/backend Any thought?

**Comment by skyhong2002** [comment]
I have no thought or solution for now. @Bogay ?
